using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GameController : MonoBehaviour
{
    // UI Elements
    public Text questionText;
    public Button[] answerButtons;
    public Text scoreText;

    // Game Data
    private List<Question> questions;
    private int currentQuestionIndex;
    private int score;

    void Start()
    {
        // Initialize game data
        LoadQuestions();
        currentQuestionIndex = 0;
        score = 0;

        // Start the game
        DisplayNextQuestion();
    }

    void LoadQuestions()
    {
        // For simplicity, hardcoded questions
        questions = new List<Question>
        {
            new Question("What is the boiling point of water?", new string[] { "100째C", "90째C", "110째C", "80째C" }, 0),
            new Question("What is the chemical symbol for water?", new string[] { "H2O", "O2", "CO2", "H2" }, 0),
            // Add more questions as needed
        };
    }
}
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
